<?php

namespace Tests\Feature;

use App\Models\Thread;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;


class ParticipateInForum extends TestCase
{
    protected $thread;
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->thread =Thread::factory()->create(); //how is this usable? no thread defined!
    }

    /** @test */
    public function unauthenticated_user_CANNOT_participate_in_threads()
    {
        $this->expectException('Illuminate\Auth\AuthenticationException');
        $reply=Reply::factory-create();
        $this->post($this->thread->path().'/replies', $reply->toArray());
    }

    /** @test */
    public function authenticated_user_may_participate_in_threads()
    {
       //for autenticated user the replies must be included in the thread
        //given that we have a user
        $user = User::factory()->create();
        //(autenticate the user with the be method))
        $this->be($user);

        //and given an existing thread
        $thread = Thread::factory()->create(['user_id'=>$user->id]);

        //when the user adds a reply to the thread
        $reply=Reply::factory()->create();
        $this->post('/threads/'.$thread->id.'/replies',$reply->toArray());

        //I use the heler method I ahd defined ahead oftime to get the url
        $this->get($this->thread->path())->assertSee($reply->body);
    }

}
